# Generated by Django 6.0.8 on 2026-08-20 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_label', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('TEACH', 'Teach me'), ('PRACTICE', 'Practice'), ('REVISION', 'Quick revision')], default='TEACH', max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=12)),
                ('resource_ids', models.JSONField(default=list)),
                ('messages', models.JSONField(default=list)),
                ('concepts', models.JSONField(default=dict)),
                ('questions', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('current_question', models.JSONField(default=dict)),
                ('report', models.JSONField(default=dict)),
                ('practice_test_id', models.UUIDField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ashvek_tutor_sessions', to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ashvek_tutor_sessions', to='academics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ashvek_tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='ashvek_stud_user_id_2b287d_idx')],
            },
        ),
    ]
