# Generated by Django 6.0.8 on 2026-08-20 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_url', models.URLField(max_length=500)),
                ('video_id', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=12)),
                ('processing_stage', models.CharField(default='Validating video', max_length=100)),
                ('processing_progress', models.PositiveSmallIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('transcript_language', models.CharField(blank=True, max_length=30)),
                ('transcript_segments', models.JSONField(default=list)),
                ('transcript_duration', models.FloatField(default=0)),
                ('current_level_order', models.PositiveSmallIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('cumulative_notes', models.TextField(blank=True)),
                ('final_challenge', models.JSONField(default=dict)),
                ('mastery_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='LearningLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list)),
                ('transcript_text', models.TextField()),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('key_concepts', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('checkpoint', models.JSONField(default=dict)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('AVAILABLE', 'Available'), ('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=12)),
                ('best_score', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='learning_paths.learningpath')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CheckpointAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_checkpoint_attempts', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning_paths.learninglevel')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning_paths.learningpath')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(fields=('user', 'video_id'), name='unique_user_youtube_path'),
        ),
        migrations.AddConstraint(
            model_name='learninglevel',
            constraint=models.UniqueConstraint(fields=('learning_path', 'order'), name='unique_learning_level_order'),
        ),
    ]
