# Generated by Django 6.0.8 on 2026-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglevel',
            name='lesson_steps',
            field=models.JSONField(default=list),
        ),
    ]
