# Generated by Django 6.0.8 on 2026-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0002_learninglevel_lesson_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglevel',
            name='best_stars',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
