# Generated by Django 6.0.8 on 2026-08-19 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('subtopics', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('color', models.CharField(default='#6D5EF5', max_length=20)),
                ('event_type', models.CharField(choices=[('STUDY', 'Study'), ('PERSONAL', 'Personal')], default='STUDY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_events', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_events', to='academics.subject')),
            ],
            options={
                'ordering': ('start_at', 'title'),
            },
        ),
    ]
