# Generated by Django 6.0.8 on 2026-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_processed_at_resource_processing_error_and_more'),
        ('tasks', '0002_plannerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='awarded_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='break_unlock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='completion_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studysession',
            name='end_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studysession',
            name='focus_state',
            field=models.CharField(choices=[('READY', 'Ready'), ('ACTIVE', 'Active'), ('PAUSED_BREAK', 'Paused for break'), ('PENALTY', 'Penalty'), ('COMPLETED_PENDING_QUIZ', 'Completed pending quiz'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='READY', max_length=32),
        ),
        migrations.AddField(
            model_name='studysession',
            name='last_state_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='penalty_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='remaining_seconds',
            field=models.PositiveIntegerField(default=2700),
        ),
        migrations.AddField(
            model_name='studysession',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='selected_resources',
            field=models.ManyToManyField(blank=True, related_name='focus_sessions', to='resources.resource'),
        ),
    ]
