# Generated by Django 6.0.8 on 2026-08-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('tasks', '0003_studysession_awarded_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='smart_break_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_break_sessions', to='ai.generatedtest'),
        ),
    ]
