# Generated by Django 6.0.8 on 2026-08-16 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('integrations', '0001_initial'),
        ('resources', '0002_alter_resource_file'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_course_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('room', models.CharField(blank=True, max_length=255)),
                ('teacher_name', models.CharField(blank=True, max_length=255)),
                ('course_state', models.CharField(blank=True, max_length=40)),
                ('course_created_at', models.DateTimeField(blank=True, null=True)),
                ('course_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='integrations.googleconnection')),
                ('rise_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_courses', to='academics.subject')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GoogleCoursework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_coursework_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('work_type', models.CharField(blank=True, max_length=40)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('alternate_link', models.URLField(blank=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('max_points', models.FloatField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursework', to='integrations.googlecourse')),
                ('rise_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_coursework', to='tasks.task')),
            ],
            options={
                'ordering': ('due_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='GoogleMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_material_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(blank=True, max_length=40)),
                ('alternate_link', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='integrations.googlecourse')),
                ('rise_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_materials', to='resources.resource')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='GoogleSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_submission_id', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('assigned_grade', models.FloatField(blank=True, null=True)),
                ('draft_grade', models.FloatField(blank=True, null=True)),
                ('late', models.BooleanField(default=False)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('google_coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='integrations.googlecoursework')),
            ],
        ),
        migrations.AddConstraint(
            model_name='googlecourse',
            constraint=models.UniqueConstraint(fields=('google_connection', 'google_course_id'), name='unique_google_course_connection'),
        ),
        migrations.AddConstraint(
            model_name='googlecoursework',
            constraint=models.UniqueConstraint(fields=('google_course', 'google_coursework_id'), name='unique_google_coursework'),
        ),
        migrations.AddConstraint(
            model_name='googlematerial',
            constraint=models.UniqueConstraint(fields=('google_course', 'google_material_id'), name='unique_google_material'),
        ),
        migrations.AddConstraint(
            model_name='googlesubmission',
            constraint=models.UniqueConstraint(fields=('google_coursework', 'google_submission_id'), name='unique_google_submission'),
        ),
    ]
