# Generated by Django 6.0.8 on 2026-08-16 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('integrations', '0002_googlecourse_googlecoursework_googlematerial_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_calendar_id', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_zone', models.CharField(blank=True, max_length=80)),
                ('access_role', models.CharField(blank=True, max_length=40)),
                ('selected', models.BooleanField(default=False)),
                ('next_sync_token', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='integrations.googleconnection')),
            ],
            options={
                'ordering': ('summary', 'google_calendar_id'),
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=80)),
                ('all_day', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('event_type', models.CharField(default='UNKNOWN', max_length=40)),
                ('html_link', models.URLField(blank=True)),
                ('recurrence', models.JSONField(default=list)),
                ('google_created_at', models.DateTimeField(blank=True, null=True)),
                ('google_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.googlecalendar')),
                ('rise_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_calendar_events', to='academics.exam')),
                ('rise_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_calendar_events', to='tasks.task')),
            ],
            options={
                'ordering': ('start_datetime', 'summary'),
            },
        ),
        migrations.AddConstraint(
            model_name='googlecalendar',
            constraint=models.UniqueConstraint(fields=('google_connection', 'google_calendar_id'), name='unique_google_calendar'),
        ),
        migrations.AddConstraint(
            model_name='googlecalendarevent',
            constraint=models.UniqueConstraint(fields=('google_calendar', 'google_event_id'), name='unique_google_calendar_event'),
        ),
    ]
