# Generated by Django 6.0.5 on 2026-08-21 14:56

import apps.adaptive_planner.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='exam-schedules/', validators=[apps.adaptive_planner.models.validate_exam_schedule_file])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs review'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamScheduleRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_label', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(default='Imported exam', max_length=200)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('raw_text', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_rows', to='academics.exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedule_rows', to='academics.subject')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='adaptive_planner.examscheduleupload')),
            ],
            options={
                'ordering': ('exam_date', 'start_time', 'subject_label', 'created_at'),
            },
        ),
    ]
