import { useState } from 'react'
import { FileText, Send, Sparkles } from 'lucide-react'
import { aiService } from './services/aiService'
import { mockNotes } from './data/mockData'

export default function ConnectedTutor() {
  const [messages, setMessages] = useState([{ role: 'assistant', content: 'Ask RISE about your subjects, priorities, or uploaded notes.' }]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const ask = async prompt => { const text = prompt || input; if (!text || busy) return; setInput(''); setBusy(true); setError(''); setMessages(items => [...items, { role: 'user', content: text }]); try { const response = await aiService.tutor({ message: text }); setMessages(items => [...items, { role: 'assistant', content: response.answer, sources: response.sources || [] }]) } catch (reason) { setError(reason.message); setMessages(items => [...items, { role: 'assistant', content: 'AI temporarily unavailable. Your deterministic RISE priorities remain available from the dashboard.' }]) } finally { setBusy(false) } }
  return <><div className="page-header"><div><p className="eyebrow">YOUR ACADEMIC COACH</p><h1>RISE Tutor</h1><p className="muted lead">Answers grounded in your academic context and uploaded notes.</p></div></div><div className="tutor-layout"><section className="chat panel"><div className="chat-head"><div className="tutor-avatar"><Sparkles size={18}/></div><div><b>RISE Tutor</b><small>Django-backed AI service with note citations</small></div><span className="online">Online</span></div><div className="messages">{messages.map((message, index) => <div className={`message ${message.role}`} key={index}><div className="message-bubble">{message.content}{message.sources?.map(source => <small className="citation" key={source.chunk_id}>Based on: {source.title}{source.page ? ` · Page ${source.page}` : ''}</small>)}</div></div>)}{busy && <div className="message assistant"><div className="message-bubble typing">RISE is thinking...</div></div>}</div><div className="quick-actions">{['Explain this topic', 'Summarize my notes', 'What should I study?', 'Find my weak topics'].map(action => <button key={action} onClick={() => ask(action)}>{action}</button>)}</div>{error && <p className="api-error">{error}</p>}<div className="chat-input"><input aria-label="Ask RISE" value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => event.key === 'Enter' && ask()} placeholder="Ask RISE anything about your semester..."/><button onClick={() => ask()} disabled={busy} aria-label="Send message"><Send size={17}/></button></div></section><aside className="source-panel panel"><p className="eyebrow">YOUR SOURCES</p><h2>Uploaded knowledge</h2><p className="muted">Tutor retrieval is scoped to your authenticated resources.</p>{mockNotes.slice(0, 4).map(note => <div className="source-item" key={note.title}><FileText size={16}/><div><b>{note.title}</b><small>{note.subject}</small></div></div>)}</aside></div></>
}
