# Generated by Django 6.0.8 on 2026-08-16 16:34

import apps.resources.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/', validators=[apps.resources.models.validate_resource_file])),
                ('resource_type', models.CharField(choices=[('NOTE', 'Note'), ('SLIDES', 'Slides'), ('DOCUMENT', 'Document'), ('QUESTION_PAPER', 'Question paper'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='NOTE', max_length=20)),
                ('source', models.CharField(choices=[('USER_UPLOAD', 'User upload'), ('GOOGLE_CLASSROOM', 'Google Classroom')], default='USER_UPLOAD', max_length=20)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_ai_ready', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.subject')),
            ],
        ),
    ]
