# Generated by Django 6.0.8 on 2026-08-16 18:17

import apps.resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='resources/', validators=[apps.resources.models.validate_resource_file]),
        ),
    ]
